### ISSUE TITLE
Test failures on main

### ISSUE THREAD

**Issue by jacobtomlinson** [dask-contrib/dask-ctl#28]
Looks like a test has started failing on `main`. 

```
=================================== FAILURES ===================================
_________________________________ test_snippet _________________________________

    def test_snippet():
        with LocalCluster(scheduler_port=8786) as _:
>           snippet = get_snippet("proxycluster-8786")
Exception in thread AsyncProcess Dask Worker process (from Nanny) watch process join:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/distributed/process.py", line 216, in _watch_process
    process.join()
AssertionError


dask_ctl/tests/test_lifecycle.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask_ctl/lifecycle.py:136: in get_snippet
    cluster = get_cluster(name)
dask_ctl/lifecycle.py:107: in get_cluster
    return loop.run_sync(_get_cluster)
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/tornado/ioloop.py:524: in run_sync
    self.start()
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/tornado/platform/asyncio.py:199: in start
    self.asyncio_loop.run_forever()
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py:530: in run_forever
    self._check_closed()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_UnixSelectorEventLoop running=False closed=True debug=False>

    def _check_closed(self):
        if self._closed:
>           raise RuntimeError('Event loop is closed')
E           RuntimeError: Event loop is closed
```

**Comment by jacobtomlinson** [comment]
Pinning has resolved this, going to open a new issue to track updating to a newer version.
